### ISSUE TITLE
Make a CLJSJS packaging

### ISSUE THREAD

**Issue by arichiardi** [replit/jq-console#74]
Dear repl.it team,
I would like to suggest a way to improve the "visibility" of this nice app. I am writing cause it would be great to have ClojuseScript direct bindings/externs for ```jq-console```, being a repl a big part of the development cycle of a ClojureScript app.

A link that explains what to do is here:
https://github.com/cljsjs/packages/wiki/Creating-Packages

Creating externs here:
https://github.com/cljsjs/packages/wiki/Creating-Externs

I could work on maintaining the packaging on ```cljsjs``` but I need some help on crafting the ```extern.js``` file.

I also found these links and I will try them out:
http://www.dotnetwise.com/Code/Externs/index.html
http://jmmk.github.io/javascript-externs-generator/

**Comment by amasad** [comment]
If you want to contribute this I'm open to it :)

**Comment by arichiardi** [comment]
Yes I am willing to do it, just help me understanding the exposed objects, only ```jqconsole``` and functions I guess are necessary for importing?

**Comment by arichiardi** [comment]
I opened a PR on this #75

**Comment by amasad** [comment]
Do you want me to merge it now?

**Comment by arichiardi** [comment]
Not yet, I am trying the integration, I will write in the PR when ok?

**Comment by amasad** [comment]
ok

**Comment by arichiardi** [comment]
Hello @amasad, I would like to ask if you can cut a release as soon as jq-console is in cljsjs, do you think it will be possible? I  working on (yet another) project that requires the "no autofocus" option and I was wondering if we could have it in 2.12...

**Comment by amasad** [comment]
released 2.12

**Comment by arichiardi** [comment]
great thanks!

**Comment by arichiardi** [comment]
Updating to `2.13.1` :+1: I guess I can close this :wink:
