### ISSUE TITLE
clearing console while in input state loses the prompt

### ISSUE THREAD

**Issue by amasad** [replit/jq-console#80]
it's gone :/

**Comment by arichiardi** [comment]
Can I ask you, what it is meant by input state? I also saw a `jqconsole-input` class in the code but I could never find it while playing with the dom.

**Comment by amasad** [comment]
when you call `jqconsole.Input()`. In a sense it's a subset of `Prompt` the difference being it doesn't record anything to the history and doesn't have the prompt class. Docs: https://github.com/replit/jq-console#jqconsoleinput

For example in a repl when you ask for the user input that's what you use in jqconsole.

**Comment by arichiardi** [comment]
Yes I am using exactly that API...maybe it is better to say that I just never seen the class `jqconsole-input` and `jqconsole-old-input` and I was wondering what was their use.

**Comment by amasad** [comment]
The use is just to stylize the input and historical input.

**Comment by arichiardi** [comment]
:+1:
